name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Copy and prepare files
        run: |
          # Create a temporary directory for the build
          mkdir -p _site
          
          # Copy root index.html
          cp index.html _site/
          
          # Copy frontend directory
          mkdir -p _site/frontend
          cp -r frontend/* _site/frontend/
          
          # Update paths in root index.html
          sed -i 's|href="./frontend/|href="/homeverse/frontend/|g' _site/index.html
          sed -i 's|window.location.href = "./frontend/|window.location.href = "/homeverse/frontend/|g' _site/index.html
          
          # Update paths in frontend files
          find _site/frontend -name "*.html" -exec sed -i 's|href="./assets/|href="/homeverse/frontend/assets/|g' {} \;
          find _site/frontend -name "*.html" -exec sed -i 's|src="./assets/|src="/homeverse/frontend/assets/|g' {} \;
          find _site/frontend -name "*.html" -exec sed -i 's|href="./|href="/homeverse/frontend/|g' {} \;
          find _site/frontend -name "*.html" -exec sed -i 's|src="./|src="/homeverse/frontend/|g' {} \;
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2